development:
  adapter: postgresql
  database: f1predict_development
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: f1predict_test
  pool: 5
  timeout: 5000
  

production:
  adapter: postgresql
  database: f1predict_production
  pool: 5
  timeout: 5000
  